################# USER ##################

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{ 
"name":"Teacher",
"email":"teacher@gmail.com",
"password": "rahasia",
"role":"TEACHER"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{ 
"email": "admin@gmail.com",
"password": "rahasia"
}


###
PUT http://localhost:5000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNzE5OTYxMjAxLCJleHAiOjE3MjI1NTMyMDF9.t5fGy95EOi-7qWDACLSS-SfSV8vpJMRjtt9OBE6sloo

{
"userId" : "2",
"name":"Teacher",
"nip":"212121",
"email":"teacher@gmail.com",
"password": "rahasia",
"role":"TEACHER"
}


###
PUT http://localhost:5000/api/users/current/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNzE5OTYxMjAxLCJleHAiOjE3MjI1NTMyMDF9.t5fGy95EOi-7qWDACLSS-SfSV8vpJMRjtt9OBE6sloo

{
"name":"Admin New"
}

###
GET http://localhost:5000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNzE5OTYxMjAxLCJleHAiOjE3MjI1NTMyMDF9.t5fGy95EOi-7qWDACLSS-SfSV8vpJMRjtt9OBE6sloo

###
GET http://localhost:5000/api/users/current
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNzE5OTYxMjAxLCJleHAiOjE3MjI1NTMyMDF9.t5fGy95EOi-7qWDACLSS-SfSV8vpJMRjtt9OBE6sloo


###
DELETE http://localhost:5000/api/users/current/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNzE5OTYxMjAxLCJleHAiOjE3MjI1NTMyMDF9.t5fGy95EOi-7qWDACLSS-SfSV8vpJMRjtt9OBE6sloo 



################# TEACHER ##################